version: '3.8'
services:
  client:
    build: ./frontend
    image: 'ai-chatbot-client'
    ports:
      - '8080:80'
    environment:
      - VITE_READ_EVENT_URL=http://localhost:4005/stream
    depends_on:
      - server

  server:
    build: ./backend
    image: 'ai-chatbot-server'
    ports:
      - '4005:4005'
